### ISSUE TITLE
Preprocess widgets lose saved preprocessors on upgrade from 3.19.0/0.3.13 -> 3.20/0.4.1

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/orange-spectroscopy#301]
I'm still trying to narrow this one down, but if anyone knows why this is happening...

A workflow saved in Orange 3.19.0 (unknown orange-spectroscopy version) does not restore the peak analysis regions in Orange 3.20.1/spec 0.4.1 or in Quasar 0.3.0 (Orange 3.20.0)/spec 0.4.1. It works fine in Orange 3.18.0/spec 0.4.1, so it's not exactly a bug in orange-spec but it's our problem now....

Related issues/possible causes so far:

1. OWPreprocess and OWIntegrate have diverged on how they build the preprocessor chain
   - I don't think this is related but may cause weird bugs down the road
2. Orange 3.19.0/spec 0.3.13 -> Orange 3.20.1/spec 0.4.1 loses preprocessor settings
3. orange-spec 0.3.13 fails on Orange 3.20: can we force an update? This is confusing for users

**Comment by stuart-cls** [comment]
Okay I think this might be related to #287 and friends. The code in `OWPreprocess.apply()` and `OWIntegrate.buildpreproc()` have diverged, even though they are nominally doing the same thing. I'll try to come up with a test to confirm this.

**Comment by stuart-cls** [comment]
Narrowed down a version matrix to reproduce this:
Orange 3.19.0 / spec 0.3.13 -> Orange 3.20.1 / spec 0.4.1

Happens for both OWIntegrate and OWPreprocess.

I was going to test 3.20.1/0.3.13 -> 3.20.1/0.4.1 but over half the widgets fail to load due to 
`ImportError: cannot import name 'get_next_name' from 'Orange.widgets.utils.annotated_data'`

**Comment by stuart-cls** [comment]
Okay I guess this is #276 ! The version soup and it working on 3.18.0/0.4.1 for some reason sent me down the wrong path.

I still think item (1) above should be consolidated and item (3) is profoundly umimpressive to users but the main thing is done here I guess.

**Comment by markotoplak** [comment]
Hmm, I will look into (1). 

Regarding (3), do you see a solution? When something in Orange core changes and makes incompatibilities, I try to release a new version or Spectroscopy before official Orange release. But I do not know how to do the reverse... The solution I see would require that also Orange knows which (minimum) versions of add-ons are compatible with it. I do not think it is a problem for users, because Spectroscopy is installed after orange. The only benefit I see is for the kind of debugging as you just did.

**Comment by stuart-cls** [comment]
Yes, I see your point. The problem arises when users upgrade their Orange (since it prompts them to) and the add-on is not upgraded. In this particular case, many widgets disappeared and users get nervous :) 

This is not an issue with the Quasar installer which includes a useful version of orange-spec, so I am promoting that solution.

**Comment by markotoplak** [comment]
Hmm, maybe upgrading Orange could ask you to also upgrade add-ons?

**Comment by stuart-cls** [comment]
That would make sense, I guess most add-ons are developed assuming you are running their latest version.
